-- MySQL Script generated by MySQL Workbench
-- Mon May 24 19:45:54 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` VARCHAR(100) NOT NULL,
  `userName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`vendors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vendors` (
  `id` VARCHAR(100) NOT NULL,
  `vendorName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`products` (
  `id` VARCHAR(100) NOT NULL,
  `vendorId` VARCHAR(100) NOT NULL,
  `userId` VARCHAR(100) NOT NULL,
  `createAt` DATE NOT NULL,
  `description` VARCHAR(250) NOT NULL,
  `link` VARCHAR(250) NOT NULL,
  `discount` INT NOT NULL,
  `validUntil` DATE NOT NULL,
  `offerName` VARCHAR(45) NOT NULL,
  `hashTags` VARCHAR(140) NOT NULL,
  `photoLink` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_idx` (`userId` ASC) VISIBLE,
  INDEX `fk_vendors_idx` (`vendorId` ASC) VISIBLE,
  CONSTRAINT `fk_users`
    FOREIGN KEY (`userId`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_vendors`
    FOREIGN KEY (`vendorId`)
    REFERENCES `mydb`.`vendors` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`rewiews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rewiews` (
  `userId` VARCHAR(100) NOT NULL,
  `productId` VARCHAR(100) NOT NULL,
  `rating` INT NULL DEFAULT NULL,
  `review` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`userId`, `productId`),
  INDEX `fk_products` (`productId` ASC) VISIBLE,
  CONSTRAINT `fk_products`
    FOREIGN KEY (`productId`)
    REFERENCES `mydb`.`products` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_users1`
    FOREIGN KEY (`userId`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
